=== neraant/first_term/kar/ЛАБА №12/Schema/third.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs ="http://www.w3.org/2001/XMLSchema">
<xs:element name="menu">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="creators">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="creator" type="xs:string"/>
                        <xs:element name="creator" type="xs:string"/>
                        <xs:element name="creator" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="menu__items">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="menu__item" type="xs:string"/>
                        <xs:element name="menu__item" type="xs:string"/>
                        <xs:element name="menu__item" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="year">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="burger__year" type="xs:string"/>
                        <xs:element name="burger__year" type="xs:string"/>
                        <xs:element name="burger__year" type="xs:string"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== neraant/first_term/kar/ЛАБА №12/third.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="style/first.css" type="text/css"?>

<menu xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Schema/third.xsd">
    <creators>
        <creator>Владмир Бургеретти</creator>
        <creator>Семён Черенок</creator>
        <creator>Бадили Тейстович</creator>
    </creators>
    <menu__items>
        <menu__item>Бургер</menu__item>
        <menu__item>Чизбургер</menu__item>
        <menu__item>Биг-тейсти</menu__item>
    </menu__items>
    <year>
        <burger__year>1285 год</burger__year>
        <burger__year>1109 год</burger__year>
        <burger__year>2023 год</burger__year>
    </year>
</menu>
